/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_17_primeiro_crud;

/**
 *
 * @author m.schmidt
 */
public class Tela_Create extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Create
     */
    public Tela_Create() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLB_Cadastro = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JTextF_Nome = new javax.swing.JTextField();
        JTextF_Sobrenome = new javax.swing.JTextField();
        JTextF_CPF = new javax.swing.JTextField();
        JBN_Adicionar = new javax.swing.JButton();
        JTextF_Celular = new javax.swing.JTextField();
        JBL_Nome = new javax.swing.JLabel();
        JBL_Sobrenome = new javax.swing.JLabel();
        JBL_CPF = new javax.swing.JLabel();
        JBL_Celular = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLB_Cadastro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JLB_Cadastro.setForeground(new java.awt.Color(0, 0, 0));
        JLB_Cadastro.setText("CADASTRO");
        jPanel1.add(JLB_Cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 120, -1));

        jPanel2.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(JTextF_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 230, -1));
        jPanel2.add(JTextF_Sobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, -1));
        jPanel2.add(JTextF_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 230, -1));

        JBN_Adicionar.setBackground(new java.awt.Color(51, 255, 51));
        JBN_Adicionar.setText("Adicionar");
        jPanel2.add(JBN_Adicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));
        jPanel2.add(JTextF_Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 230, -1));

        JBL_Nome.setText("Nome:");
        jPanel2.add(JBL_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, -1));

        JBL_Sobrenome.setText("Sobrenome:");
        jPanel2.add(JBL_Sobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        JBL_CPF.setText("CPF:");
        jPanel2.add(JBL_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        JBL_Celular.setText("Celular:");
        jPanel2.add(JBL_Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 360, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Create().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JBL_CPF;
    private javax.swing.JLabel JBL_Celular;
    private javax.swing.JLabel JBL_Nome;
    private javax.swing.JLabel JBL_Sobrenome;
    private javax.swing.JButton JBN_Adicionar;
    private javax.swing.JLabel JLB_Cadastro;
    private javax.swing.JTextField JTextF_CPF;
    private javax.swing.JTextField JTextF_Celular;
    private javax.swing.JTextField JTextF_Nome;
    private javax.swing.JTextField JTextF_Sobrenome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
